name: ci
description: Executes Dart specific CI steps.
inputs:
  type:
    description: The type of CI to run.
    required: true
  relay-endpoint:
    description: 'The endpoint of the relay e.g. relay.walletconnect.com'
    required: false
    default: 'wss://relay.walletconnect.com'
  project-id:
    description: 'WalletConnect project id'
    required: true

runs:
  using: composite
  steps:
    # General Tests
    - name: Install packages
      shell: bash
      run: flutter pub get

    - name: Verify formatting and analyze project source
      shell: bash
      run: dart format --output=none --set-exit-if-changed .

    - name: Analyze project source
      shell: bash
      run: flutter analyze

    # Unit and Integration Tests
    - name: Run tests
      if: inputs.type == 'integration-tests'
      shell: bash
      env:
        RELAY_ENDPOINT: ${{ inputs.relay-endpoint }}
        PROJECT_ID: ${{ inputs.project-id }}
      run: flutter test --dart-define=RELAY_ENDPOINT=$RELAY_ENDPOINT --dart-define=PROJECT_ID=$PROJECT_ID
    