name: ci
description: Installs dependencies

runs:
  using: composite
  steps:
    # General Tests
    - name: Install packages
      shell: bash
      run: flutter pub get

    # - name: Generate code
    #   shell: bash
    #   run: dart run build_runner build -d

    - name: Install packages for example
      shell: bash
      run: cd example/dapp && flutter pub get && cd ../..

    - name: Verify formatting and analyze project source
      shell: bash
      run: dart format --output=none --set-exit-if-changed .

    # - name: Analyze project source
    #   shell: bash
    #   run: flutter analyze
    